# -*- coding: utf-8 -*-
"""MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bUlmrVRqb-vq1GADRL4CQGXntofnksf-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.utils import to_categorical

from sklearn.metrics import(accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report,ConfusionMatrixDisplay)

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

print("Training Images Shape :", X_train.shape)
print("Training Labels Shape :", y_train.shape)

print("Testing Images Shape  :", X_test.shape)
print("Testing Labels Shape  :", y_test.shape)

classes = [
    "T-shirt/Top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle Boot"
]

plt.figure(figsize=(12,5))

for i in range(10):

    plt.subplot(2,5,i+1)

    plt.imshow(X_train[i], cmap="gray")

    plt.title(classes[y_train[i]])

    plt.axis("off")

plt.suptitle("Sample Fashion-MNIST Images")

plt.tight_layout()

plt.show()

plt.figure(figsize=(8,5))

sns.countplot(x=y_train)

plt.title("Class Distribution")

plt.xlabel("Class")

plt.ylabel("Number of Images")

plt.xticks(range(10), classes, rotation=45)

plt.tight_layout()

plt.show()

print("Before Flattening")

print("Training Shape:", X_train.shape)

print("Testing Shape :", X_test.shape)

X_train = X_train.reshape(60000, 784)

X_test = X_test.reshape(10000, 784)

X_train = X_train / 255.0

X_test = X_test / 255.0

y_train_cat = to_categorical(y_train)

y_test_cat = to_categorical(y_test)

print("After Preprocessing")

print("Training Features :", X_train.shape)

print("Testing Features  :", X_test.shape)

print("Training Labels   :", y_train_cat.shape)

print("Testing Labels    :", y_test_cat.shape)

model = Sequential([
    Input(shape=(784,)),

    Dense(128, activation="relu"),

    Dense(64, activation="relu"),

    Dense(10, activation="softmax")
])

model.summary()

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    X_train,
    y_train_cat,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

y_pred_prob = model.predict(X_test)

y_pred = np.argmax(y_pred_prob, axis=1)

y_true = np.argmax(y_test_cat, axis=1)
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted")
recall = recall_score(y_true, y_pred, average="weighted")
f1 = f1_score(y_true, y_pred, average="weighted")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-score :", f1)

print(classification_report(y_true, y_pred, target_names=classes))
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=classes,
    yticklabels=classes
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.tight_layout()
plt.show()

!pip install scikeras
from scikeras.wrappers import KerasClassifier

from sklearn.model_selection import RandomizedSearchCV

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, Dropout
from tensorflow.keras.optimizers import Adam, SGD, RMSprop

def create_model(
    hidden_layers=2,
    neurons=128,
    learning_rate=0.001,
    activation="relu",
    optimizer="adam",
    dropout_rate=0.0
):

    model = Sequential()

    model.add(Input(shape=(784,)))

    for i in range(hidden_layers):

        model.add(Dense(neurons, activation=activation))

        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))

    model.add(Dense(10, activation="softmax"))

    # The model should be returned uncompiled for KerasClassifier
    return model

keras_model = KerasClassifier(
    model=create_model,
    loss="categorical_crossentropy", # Added loss
    metrics=["accuracy"], # Added metrics
    verbose=0
)

param_dist = {

    "model__hidden_layers":[1,2,3],

    "model__neurons":[32,64,128,256],

    "model__learning_rate":[0.1,0.01,0.001],

    "model__activation":[
        "relu",
        "tanh",
        "sigmoid"
    ],

    "model__optimizer":[
        "adam",
        "sgd",
        "rmsprop"
    ],

    "model__dropout_rate":[0.0,0.2,0.5],

    "batch_size":[16,32,64,128],

    "epochs":[10,20,30]

}

random_search = RandomizedSearchCV(

    estimator=keras_model,

    param_distributions=param_dist,

    n_iter=6,

    cv=3,

    scoring="accuracy",

    random_state=42,

    n_jobs=-1

)

!pip install scikit-learn==1.5.2 scikeras==0.13.0

random_search.fit(X_train, y_train)

print("Best Parameters")

print(random_search.best_params_)

print()

print("Best Cross Validation Accuracy")

print(random_search.best_score_)

best_model = random_search.best_estimator_

test_accuracy = best_model.score(
    X_test,
    y_test
)

print("Testing Accuracy")

print(test_accuracy)

plt.figure(figsize=(8,5))

plt.plot(history.history["accuracy"], label="Training Accuracy")

plt.title("Training Accuracy vs Epoch")

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.legend()

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history["val_accuracy"], label="Validation Accuracy")

plt.title("Validation Accuracy vs Epoch")

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.legend()

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history["loss"])

plt.title("Training Loss vs Epoch")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history["val_loss"])

plt.title("Validation Loss vs Epoch")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.grid(True)

plt.show()

results = pd.DataFrame(random_search.cv_results_)

plt.figure(figsize=(10,5))

plt.plot(results["mean_test_score"], marker="o")

plt.title("Random Search Accuracy")

plt.xlabel("Iteration")

plt.ylabel("Cross Validation Accuracy")

plt.grid(True)

plt.show()

baseline_accuracy = accuracy

optimized_accuracy = test_accuracy

plt.figure(figsize=(6,5))

plt.bar(
    ["Baseline","Optimized"],
    [baseline_accuracy, optimized_accuracy]
)

plt.title("Baseline vs Optimized Model")

plt.ylabel("Accuracy")

plt.show()